services:
  postgres:
    build:
      context: ../../casulsulvania-db
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./_local_data:/var/lib/postgresql/data

  app:
    build:
      context: ../../casulsulvania
      tags:
        - "registry.digitalocean.com/bam/casulsulvania"
    environment:
      BASE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:password@postgres/postgres?sslmode=disable
    env_file: .env.local
    depends_on:
      - postgres
    ports:
      - 3000:80
